apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  spring.datasource.url: "jdbc:mysql://117.73.12.78:30006/dome?useSSL=false&serverTimezone=UTC"
  spring.redis.host: "117.73.12.78"
  spring.redis.port: "30379"
  spring.redis.password: "redis"
  spring.rabbitmq.host: "117.73.12.78"
  spring.rabbitmq.username: "rabbitmq"
  spring.rabbitmq.password: "rabbitmq"
  aliyun.oss.endpoint: "oss-innet.cn-north-3.inspurcloudoss.com"
  aliyun.oss.bucketName: "dome01" 