apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
type: Opaque
data:
  spring.datasource.username: cm9vdA==  # root
  spring.datasource.password: cm9vdDEyMw==  # root123
  aliyun.oss.accessKeyId: WWpBM1pUWmxZVVRZbU1NeTAwTlROalxJWVlPRFF0WlRnMWZtVXlOR0UzWkRBNg==  # YjA3ZTZlYTEtYmM3Ny00NTNjLWIyOGQtZTg1ZmUyNGE3ZGE2
  aliyun.oss.accessKeySecret: TmpnOU5qSmpaVFppdE5tRjNOYzAwTW1JNkxXSTVZekF0TWpJME1tWXhZakF5TlRNeg==  # Njg5NjJjZTItNmY3NC00MmI2LWI5YzAtMjA0YmYxYjAyNTMz 